version: "2.1"

volumes:
    influxdb:

services:
    wifi:
        build: wifi
        network_mode: "host"
        labels:
            io.balena.features.dbus: '1'
        cap_add:
            - NET_ADMIN
        environment:
            DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

    influxdb:
        restart: always
        build: ./influxdb
        volumes:
        - 'influxdb:/data'