version: '2.1'

volumes:
  data:

services:

  log:
    build: log
    volumes:
      - 'data:/log'
    expose:
      - '80'

  # battery:
  #   build: battery
  #   privileged: true
  #   labels:
  #     io.balena.features.dbus: '1'
  #   environment:
  #     DBUS_SYSTEM_BUS_ADDRESS: 'unix:path=/host/run/dbus/system_bus_socket'

  wifi:
    build: wifi
    network_mode: 'host'
    labels:
      io.balena.features.dbus: '1'
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: 'unix:path=/host/run/dbus/system_bus_socket'

  db:
    build: db
    volumes:
      - 'data:/db'

  phidget:
    build: phidget
    volumes:
      - 'data:/phidget'
    expose:
      - '5661'
    privileged: true
    labels:
      io.balena.features.kernel-modules: true

  control:
    build: control
    volumes:
      - 'data:/control'
    expose:
      - '3000'
    privileged: true
    labels:
      io.balena.features.kernel-modules: true
    depends_on:
      - log
      - phidget
      - db

  ui:
    build: ui
    volumes:
      - 'data:/ui'
    privileged: true
    labels:
      io.balena.features.kernel-modules: true
      # io.balena.features.dbus: '1'
    depends_on:
      - log