version: '2.1'

volumes:
  data:

services:

  log:
    build: log
    volumes:
      - 'data:/data'
    expose:
      - '80'
  
  # nginx:
  #   build : nginx
  #   ports:
  #       - '80:80'
  #       - '443:443'

  # battery:
  #   build: battery
  #   privileged: true
  #   labels:
  #     io.balena.features.dbus: '1'
  #   environment:
  #     DBUS_SYSTEM_BUS_ADDRESS: 'unix:path=/host/run/dbus/system_bus_socket'

  wifi-connect:
    build: wifi-connect
    ports:
      - '80:80'
    network_mode: 'host'
    labels:
      io.balena.features.dbus: '1'
    cap_add:
      - NET_ADMIN
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
      - 'PORTAL_LISTENING_PORT=80'

  influxdb:
    build: influxdb
    volumes:
      - 'data:/data'
    privileged: true
    expose:
      - '8086'

  grafana:
    build: grafana
    ports:
      - '80'
    volumes:
      - 'data:/data'
    environment:
        - 'GF_PATHS_DATA=/data/grafana'
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_SESSION_PROVIDER=memory'
        # - 'GF_AUTH_ANONYMOUS_ENABLED=true'
    depends_on:
      - influxdb

  phidget:
    build: phidget
    volumes:
      - 'data:/data'
    expose:
      - '5661'
    privileged: true
    labels:
      io.balena.features.kernel-modules: true

  control:
    build: control
    volumes:
      - 'data:/data'
    expose:
      - '3000'
    privileged: true
    labels:
      io.balena.features.kernel-modules: true
    depends_on:
      - log
      - phidget
      # - db

  ui:
    build: ui
    volumes:
      - 'data:/data'
    privileged: true
    labels:
      io.balena.features.kernel-modules: true
    depends_on:
      - log