version: '2.1'

volumes:
  data:
  www:

services:

  log:
    build: log
    expose:
      - '80'
    volumes:
      - 'data:/data'
  
  nginx:
    build : nginx
    ports:
        - '80:80'
        - '443:443'
    volumes:
      - 'www:/www'

  wifi-connect:
    build: wifi-connect
    network_mode: 'host'
    ports:
      - '81:81'
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: '1'
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
      - 'PORTAL_LISTENING_PORT=81'

  influxdb:
    build: influxdb
    privileged: true
    expose:
      - '8086'
    volumes:
      - 'data:/data'
    environment:
      - 'INFLUXDB_DATA_QUERY_LOG_ENABLED=false'
      - 'INFLUXDB_DATA_TRACE_LOGGING_ENABLED=false'
      - 'INFLUXDB_HTTP_LOG_ENABLED=false'
      - 'INFLUXDB_LOGGING_SUPPRESS_LOGO=true'

  grafana:
    build: grafana
    expose:
      - '80'
    volumes:
      - 'data:/data'
    environment:
        - 'GF_PATHS_DATA=/data/grafana'
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_SESSION_PROVIDER=memory'
        # - 'GF_AUTH_ANONYMOUS_ENABLED=true'
    depends_on:
      - influxdb

  phidget:
    build: phidget
    privileged: true
    expose:
      - '5661'
    volumes:
      - 'data:/data'
    labels:
      io.balena.features.kernel-modules: true

  control:
    build: control
    privileged: true
    ports:
      - '3000:3000'
    volumes:
      - 'data:/data'
    labels:
      io.balena.features.kernel-modules: true
      io.balena.features.supervisor-api: '1'
    depends_on:
      - log
      - phidget
      - influxdb

  ui:
    build: ui
    privileged: true
    volumes:
      - 'data:/data'
      - 'www:/www'
    labels:
      io.balena.features.kernel-modules: true
    depends_on:
      - log