version: "2.1"

volumes:
  db:

services:
  battery:
    build: battery
    privileged: true

  wifi:
    build: wifi
    network_mode: "host"
    labels:
      io.balena.features.dbus: '1'
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

  db:
    restart: always
    build: db
    volumes:
      - 'db:/data'