FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10-build as build

WORKDIR /usr/src/log
COPY ./package.json .
RUN JOBS=MAX npm install --unsafe-perm --production

FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10-run

WORKDIR /usr/src/log
COPY ./ ./
COPY --from=build /usr/src/log/node_modules ./node_modules

CMD ["node", "/usr/src/log/src/index.js"]