function state() {
  const systemState = {
    cellAir: {
      label: 'Air',
      chartTitle: 'Cell Air Flow',
      editTitle: 'Cell Air',
      units: 'SCCM',
      max: 1000,
      event: 'cellair',
      setpoint: 200,
      deviceSetpoint: 0,
      actual: 0,
    },
    cellAirPressure: {
      chartTitle: 'Cell Air Pressure',
      units: 'PSI',
      event: 'cellair',
      actual: 0,
    },
    cellTemperature: {
      label: 'Temp',
      chartTitle: 'Cell Temperature',
      editTitle: 'Cell Temp',
      units: `${String.fromCharCode(176)}C`,
      max: 200,
      event: 'celltemperature',
      setpoint: 120,
      deviceSetpoint: 0,
      pidIdentifier: 'cell',
      kp: 0,
      ki: 0,
      kd: 0,
      output: 0,
      actual: 0,
    },
    cellDiskSpeed: {
      label: 'Disc',
      chartTitle: 'Disc Speed',
      units: 'RPM',
      min: 0.1,
      max: 5,
      event: 'diskrpm',
      setpoint: 1,
      deviceSetpoint: 0,
      actual: 0,
    },
    cellPressure: {
      label: 'Pressure',
      chartTitle: 'Cell Pressure',
      units: 'PSIG',
      max: 15,
      event: 'cellpressure',
      setpoint: 3,
      deviceSetpoint: 0,
      actual: 0,
    },
    diversionValve: {
      label: 'Sample Flow',
      event: 'diversionvalve',
      setpoint: false,
      actual: false,
      isEnabled: () => systemState.laserOutput.actual > 0,
      // isEnabled: () => true,
    },
    laserHardInterlock: {
      label: 'Interlock',
      event: 'laserhardinterlock',
      setpoint: true,
      actual: true,
      isEnabled: () => false,
    },
    laserInterlock1: {
      label: 'Lock 1',
      event: 'laserState',
      setpoint: true,
      actual: true,
      isEnabled: () => false,
    },
    laserInterlock2: {
      label: 'Lock 2',
      event: 'laserState',
      setpoint: true,
      actual: true,
      isEnabled: () => false,
    },
    laserEnabled: {
      label: 'Power',
      event: 'lasersoftinterlock',
      flip: true,
      setpoint: false,
      actual: false,
      isEnabled: () => !systemState.laserHardInterlock.actual && systemState.cellDiskSpeed.actual > 0,
    },
    laserPilot: {
      label: 'Pilot',
      event: 'laserpilot',
      setpoint: false,
      actual: false,
      isEnabled: () => true,
    },
    laserOutput: {
      label: 'Power',
      chartTitle: 'Laser Power',
      units: '%',
      min: 20,
      max: 100,
      event: 'laserpower',
      setpoint: 0,
      deviceSetpoint: 0,
      actual: 0,
      isEnabled: () => systemState.laserEnabled.actual,
    },
    laserPowerCalculated: {
      label: 'Calc Power',
      chartTitle: 'Calculated Laser Power',
      units: '%',
      event: 'laserpowercalculated',
      deviceSetpoint: 0,
      actual: 0,
    },
    laserBoxTemperature: {
      label: 'Internal',
      chartTitle: 'Laser Internal Temperature',
      units: `${String.fromCharCode(176)}C`,
      event: 'laser.temperature',
      actual: 0,
    },
    laserHousingTemperature: {
      label: 'Housing',
      chartTitle: 'Laser Housing Temperature',
      units: `${String.fromCharCode(176)}C`,
      event: 'lasertemperature',
      actual: 0,
    },
    fidAir: {
      label: 'Air',
      chartTitle: 'FID Air Flow',
      editTitle: 'FID Air',
      units: 'SCCM',
      max: 500,
      event: 'fidair',
      setpoint: 400,
      deviceSetpoint: 0,
      actual: 0,
    },
    fidAirPressure: {
      chartTitle: 'FID Air Pressure',
      units: 'PSI',
      event: 'fidair',
      actual: 0,
    },
    fidHydrogen: {
      label: `H${String.fromCharCode(0x2082)}`,
      chartTitle: 'FID Hydrogen Flow',
      editTitle: 'FID Hydrogen',
      units: 'SCCM',
      max: 100,
      event: 'fidhydrogen',
      setpoint: 50,
      deviceSetpoint: 0,
      actual: 0,
    },
    fidHydrogenPressure: {
      chartTitle: 'FID Hydrogen Pressure',
      units: 'PSI',
      event: 'fidhydrogen',
      actual: 0,
    },
    fidTemperature: {
      label: 'Temp',
      chartTitle: 'FID Temperature',
      editTitle: 'FID Temp',
      units: `${String.fromCharCode(176)}C`,
      max: 450,
      event: 'fidtemperature',
      setpoint: 400,
      deviceSetpoint: 0,
      pidIdentifier: 'fid',
      kp: 0,
      ki: 0,
      kd: 0,
      actual: 0,
    },
    fid: {
      label: 'Response',
      chartTitle: 'FID Response',
      units: 'mV',
      event: 'fid',
      actual: 0,
      voltage: 0,
    },
    fidIgniter: {
      label: 'Igniter',
      event: 'fidigniter',
      setpoint: false,
      actual: false,
      isEnabled: () => !systemState.fidFlame.actual,
    },
    fidFlame: {
      label: 'Flame',
      event: 'fidignited',
      setpoint: false,
      actual: false,
      isEnabled: () => false,
    },
    fidFlameTemperature: {
      label: 'Flame Temp',
      event: 'fid.flametemp',
      chartTitle: 'FID Flame Temperature',
      units: `${String.fromCharCode(176)}C`,
      actual: 0,
    },
    computerUptime: {
      label: 'Uptime',
      units: '',
      event: 'computer.time',
      actual: 0,
    },
    computerTemperature: {
      label: 'CPU Temp',
      chartTitle: 'CPU Temperature',
      sampleRate: 1000,
      units: `${String.fromCharCode(176)}C`,
      event: 'computer.temperature',
      actual: 0,
    },
    computerCpu: {
      label: 'CPU',
      chartTitle: 'CPU Usage',
      sampleRate: 1000,
      units: '%',
      event: 'computer.cpu',
      actual: 0,
    },
    computerMemory: {
      label: 'Memory',
      chartTitle: 'Memory Usage',
      sampleRate: 1000,
      units: '%',
      event: 'computer.memory',
      actual: 0,
    },
    computerFsSize: {
      label: 'Storage',
      sampleRate: 1000,
      units: 'GB',
      event: 'computer.fssize',
      actual: 0,
    },
    computerFsUsed: {
      label: 'Used',
      sampleRate: 1000,
      units: 'GB',
      event: 'computer.fsused',
      actual: 0,
    },
    computerIp: {
      label: 'IP',
      units: '',
      event: 'computer.ip',
      actual: '',
    },
    cellCompartmentLeak: {
      label: 'Leak',
      units: '',
      event: 'cellcompartment.leak',
      actual: false,
    },
    cellCompartmentLeakVolts: {
      label: 'Leak Volts',
      sampleRate: 500,
      chartTitle: 'Cell Compartment Leak Volts',
      units: 'V',
      event: 'cellcompartment.leakvolts',
      actual: 0,
    },
    redLight: {
      event: 'redlight',
      actual: false,
    },
    orangeLight: {
      event: 'orangelight',
      actual: false,
    },
    greenLight: {
      event: 'greenlight',
      actual: false,
    },
  };

  systemState.cellAir.secondary = systemState.cellAirPressure;
  systemState.fidAir.secondary = systemState.fidAirPressure;
  systemState.fidHydrogen.secondary = systemState.fidHydrogenPressure;

  return systemState;
}

module.exports = (container) => {
  container.service('systemState', state, 'env');
};
