FROM balenalib/%%BALENA_MACHINE_NAME%%:buster

RUN install_packages \
      fontconfig-config \
      fonts-dejavu-core \
      libfontconfig1 \
      ucf \
      jq \
      wget

# COPY ./provisioning /usr/share/grafana/conf/provisioning
COPY ./*.ini /usr/share/grafana/conf/
COPY ./*.sh /usr/src/grafana/
RUN chmod +x /usr/src/grafana/*.sh
RUN /usr/src/grafana/download.sh "%%BALENA_ARCH%%"

RUN dpkg -i /tmp/grafana.deb && rm /tmp/grafana.deb

CMD ["/bin/sh","/usr/src/grafana/entry.sh"]