FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10-build as build

WORKDIR /usr/src/control
COPY ./package.json .
RUN JOBS=MAX npm install --unsafe-perm --production

FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10-run

WORKDIR /usr/src/control
COPY ./ ./
COPY --from=build /usr/src/control/node_modules ./node_modules

CMD ["bash", "/usr/src/control/start.sh"]