FROM balenalib/%%RESIN_MACHINE_NAME%%-debian

RUN install_packages dnsmasq wireless-tools

WORKDIR /usr/src/wifi-connect

RUN curl https://api.github.com/repos/balena-io/wifi-connect/releases/tags/v4.3.1 -s \
    | grep -hoP 'browser_download_url": "\K.*%%RESIN_ARCH%%\.tar\.gz' \
    | xargs -n1 curl -Ls \
    | tar -xvz -C /usr/src/wifi/

COPY start.sh .

CMD ["bash", "start.sh"]