FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:3.12

WORKDIR /usr/src/influxdb

RUN apk add influxdb
RUN mkdir -p /root/.influxdb/data
RUN echo "LABEL=influxdb /root/.influxdb/data ext4 rw,relatime,discard,data=ordered 0 2" >> /etc/fstab

COPY ./*.conf /etc/influxdb/

COPY start.sh .

CMD ["bash", "/usr/src/influxdb/start.sh"]