FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine:3.12

RUN apk add influxdb

RUN echo "LABEL=influxdb /mnt/influxdb ext4 rw,relatime,discard,data=ordered 0 2"  >> /etc/fstab

COPY influxdb.conf /etc/influxdb

CMD ["bash", "start.sh"]